name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: unit test
      run: make test
  
    - uses: actions/upload-artifact@v4
      with:
        name: unit_test log
        path: ./unit_test.log
        
    - name: check unit_test log
      run: |
        if grep FAIL unit_test.log ; then
          echo "unit test fail"
          exit 1
        fi
        
    - name: make
      run: make
